duplicate_keys:
  - CohortName
  - StudyID
  - UniqueStudyID
  - MRI_fieldStrength
  - studyTimepoint

demographic_merge_keys:
  - CohortName
  - project
  - StudyID
  - subject
  - studyTimepoint
  - session